language: ruby
rvm:
  2.1.2

env:
  - DB=postgresql

addons:
  postgresql: 9.3

script:
  - RAILS_ENV=test bundle exec rake --trace test
#  - karma start --single-run --browsers PhantomJS test/javascripts/config/unit.js

before_script:
  - psql -c 'create database moments_test' -U postgres
  - RAILS_ENV=test bundle exec rake --trace db:structure:load
#  - npm install karma
  - npm install bower
  - bower install