# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.define 'local' do |config|

    config.vm.provider :virtualbox do |vb|
      vb.customize ['modifyvm', :id, '--memory', '512']
    end

    config.vm.box = 'precise64'

    config.vm.provision 'ansible' do |ansible|
      ansible.playbook = 'provisioning/playbook.yml'
    end
  end

  config.vm.define 'ocean' do |config|
    config.vm.box = 'dummy'

    config.vm.provider :managed do |managed, override|
      managed.server = '188.226.164.42'
      override.ssh.username = 'deploy'
      override.ssh.private_key_path = '/Users/loki/.ssh/id_rsa'
    end

    config.vm.provision 'ansible' do |ansible|
      ansible.playbook = 'provisioning/playbook.yml'
      ansible.tags = 'nodejs'
      ansible.skip_tags = 'deployer'
    end
  end
end
