---
- hosts: all
  sudo: yes

  tasks:
    # updates apt cache once a week
    - apt: update_cache=true cache_valid_time=604800
      tags: apt-cache

    - apt: pkg={{item}}
      with_items:
        - make
        - libpq-dev
        - g++
        - vim-nox
        - python-pycurl
        - libxslt1-dev
        - libxml2-dev
        - imagemagick
      tags: packages

    - include: deployer.yml
      tags: deployer

    - include: nodejs.yml
      tags: nodejs

    - include: ruby.yml
      tags: ruby

    - include: postgresql.yml
      tags: postgresql
      vars:
        type: web
        total_memory: 178956970 # 1/3 of 512Mb
        max_connections: 20

    - include: nginx.yml
      tags: nginx
      vars:
        application: moments
        rails_env: production

    - include: redis.yml
      tags: redis
      vars:
        maxmemory: 85mb
        maxmemory_policy: allkeys-lru

    - include: rails.yml
      tags: rails
      vars:
        application: moments
        rails_env: production

  handlers:
    - name: restart postgresql
      service: name=postgresql state=restarted

    - name: restart redis
      service: name=redis-server state=restarted

    - name: restart nginx
      service: name=nginx state=restarted
