development: &defaults
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *defaults
  database: moments_development
  host: localhost
  username: postgres
  password:

test:
  <<: *defaults
  database: moments_test
  username: postgres
  password:

production:
  <<: *defaults
  database: moments

