development: &defaults
  adapter: postgresql
  host: localhost
  database: moments_development
  encoding: unicode
  pool: 5
  username: postgres
  password:

test:
  <<: *defaults
  database: moments_test

production:
  database: moments_production

