development: &defaults
  secret_key_base: dummy
  dragonfly: dummy

  aws_access_key_id: dummy
  aws_secret_access_key: dummy
  aws_photos_bucket: dummy

test:
  <<: *defaults

production:
  <<: *defaults
  secret_key_base: dummy

  aws_photos_bucket: dummy